Repository Autostronomy/AstroPhot, pull requests merged in 2023-02, with the labels that each got.

#16 Dev to main: adding badges to README
  .github/workflows/documentation.yaml
  .github/workflows/testing.yaml
  README.md
Labels: enhancement

#17 Dev to main: updates to github page documentation
  .github/workflows/documentation.yaml
  .github/workflows/testing.yaml
  .gitignore
  README.md
  docs/citation.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/install.rst
Labels: documentation

#24 Adding minimal configuration file interface. Updates to doc website
  .github/workflows/testing.yaml
  README.md
  autoprof/__init__.py
  autoprof/parse_config/basic_config.py
  docs/configfile_interface.rst
  docs/getting_started.rst
  docs/index.rst
  docs/install.rst
  docs/tutorials/simple_config.py
  media/AP_logo_white.png
  setup.py
Labels: documentation, enhancement

#26 more helpful error message if users try to run autoprof at terminal with no arguments
  autoprof/__init__.py
Labels: documentation, user experience

#28 Added more unit tests
  .github/workflows/documentation.yaml
  .github/workflows/testing.yaml
  autoprof/__init__.py
  autoprof/image/image_object.py
  autoprof/image/target_image.py
  autoprof/image/window_object.py
  autoprof/models/core_model.py
  autoprof/models/group_model_object.py
  autoprof/models/model_object.py
  tests/test_fit.py
  tests/test_image.py
  tests/test_model.py
Labels: enhancement

#31 Revert "Added more unit tests"
  .github/workflows/documentation.yaml
  .github/workflows/testing.yaml
  autoprof/__init__.py
  autoprof/image/image_object.py
  autoprof/image/target_image.py
  autoprof/image/window_object.py
  autoprof/models/core_model.py
  autoprof/models/group_model_object.py
  autoprof/models/model_object.py
  tests/test_fit.py
  tests/test_image.py
  tests/test_model.py
Labels: bug

#35 Added new tests. fixed workflow to now properly install AutoProf
  .github/workflows/documentation.yaml
  .github/workflows/testdev.yml
  .github/workflows/testing.yaml
  CONTRIBUTING.md
  autoprof/image/image_object.py
  autoprof/image/target_image.py
  autoprof/image/window_object.py
  autoprof/models/core_model.py
  autoprof/models/group_model_object.py
  autoprof/models/model_object.py
  tests/test_fit.py
  tests/test_image.py
  tests/test_model.py
Labels: enhancement

#43 change sample interface to __call__
  README.md
  autoprof/__init__.py
  autoprof/fit/base.py
  autoprof/fit/gradient.py
  autoprof/fit/iterative.py
  autoprof/fit/langevin.py
  autoprof/fit/lm.py
  autoprof/models/core_model.py
  autoprof/models/edgeon_model.py
  autoprof/models/galaxy_model_object.py
  autoprof/models/group_model_object.py
  autoprof/models/joint_model.py
  autoprof/models/model_object.py
  autoprof/models/sky_model_object.py
  autoprof/models/star_model_object.py
  autoprof/parse_config/basic_config.py
  autoprof/plots/image.py
  docs/getting_started.rst
  docs/index.rst
  docs/install.rst
  docs/tutorials/CustomModels.ipynb
  docs/tutorials/FittingMethods.ipynb
  docs/tutorials/GettingStarted.ipynb
  setup.py
  tests/test_model.py
Labels: refactor, user experience

#49 shifted imports & added blank Lines
  autoprof/fit/gradient.py
  autoprof/image/image_object.py
  autoprof/image/window_object.py
  autoprof/models/_model_methods.py
  autoprof/models/_shared_methods.py
  autoprof/models/edgeon_model.py
  autoprof/models/galaxy_model_object.py
  autoprof/models/group_model_object.py
  autoprof/models/nonparametric_model.py
  autoprof/models/parameter_object.py
  autoprof/models/sersic_model.py
  autoprof/models/warp_model.py
  autoprof/plots/profile.py
  autoprof/utils/conversions/dict_to_hdf5.py
  autoprof/utils/initialize/__init__.py
  autoprof/utils/initialize/construct_psf.py
  autoprof/utils/interpolate.py
  autoprof/utils/isophote/integrate.py
  autoprof/utils/operations.py
Labels: documentation

#53 These changes are correct?
  autoprof/image/image_object.py
Labels: documentation

#57 Adding MCMC methods for AutoProf
  autoprof/fit/__init__.py
  autoprof/fit/hmc.py
  autoprof/fit/iterative.py
  autoprof/fit/langevin.py
  autoprof/fit/mhmcmc.py
  autoprof/image/window_object.py
  autoprof/models/_shared_methods.py
  autoprof/models/core_model.py
  autoprof/models/group_model_object.py
  autoprof/models/parameter_object.py
  autoprof/plots/image.py
  autoprof/utils/initialize/center.py
  autoprof/utils/initialize/initialize.py
  autoprof/utils/isophote/extract.py
  docs/index.rst
  docs/tutorials.rst
  docs/tutorials/CustomModels.pdf
  docs/tutorials/GettingStarted.pdf
  docs/tutorials/GroupModels.pdf
  docs/tutorials/JointModels.ipynb
  docs/tutorials/JointModels.pdf
  docs/tutorials/ModelZoo.pdf
  requirements.txt
  setup.py
  tests/test_fit.py
Labels: enhancement
