Repository Autostronomy/AstroPhot, pull requests merged in 2023-03, with the labels that each got.

#59 Adding model tests
  autoprof/fit/hmc.py
  autoprof/models/_shared_methods.py
  autoprof/models/edgeon_model.py
  autoprof/models/nonparametric_model.py
  autoprof/models/parameter_object.py
  autoprof/models/sersic_model.py
  tests/test_model.py
  tests/utils.py
Labels: enhancement

#62 Adding unit tests for image objects
  .gitignore
  autoprof/image/image_object.py
  autoprof/image/target_image.py
  tests/test_fit.py
  tests/test_image.py
  tests/test_image_list.py
  tests/test_model.py
Labels: unit test

#63 Unit tests for utils
  autoprof/utils/angle_operations.py
  autoprof/utils/initialize/segmentation_map.py
  autoprof/utils/interpolate.py
  autoprof/utils/operations.py
  tests/test_utils.py
  tests/utils.py
Labels: unit test

#69 Jacobian Image object, more flexible, remove Joint_Model object
  autoprof/fit/iterative.py
  autoprof/fit/lm.py
  autoprof/image/__init__.py
  autoprof/image/image_object.py
  autoprof/image/jacobian_image.py
  autoprof/image/model_image.py
  autoprof/image/target_image.py
  autoprof/image/window_object.py
  autoprof/models/__init__.py
  autoprof/models/_shared_methods.py
  autoprof/models/core_model.py
  autoprof/models/edgeon_model.py
  autoprof/models/exponential_model.py
  autoprof/models/flatsky_model.py
  autoprof/models/foureirellipse_model.py
  autoprof/models/galaxy_model_object.py
  autoprof/models/gaussian_model.py
  autoprof/models/group_model_object.py
  autoprof/models/joint_model.py
  autoprof/models/model_object.py
  autoprof/models/moffat_model.py
  autoprof/models/nonparametric_model.py
  autoprof/models/nuker_model.py
  autoprof/models/parameter_object.py
  autoprof/models/planesky_model.py
  autoprof/models/psf_model.py
  autoprof/models/ray_model.py
  autoprof/models/sersic_model.py
  autoprof/models/superellipse_model.py
  autoprof/models/warp_model.py
  autoprof/models/wedge_model.py
  docs/tutorials/CustomModels.ipynb
  docs/tutorials/GroupModels.ipynb
  docs/tutorials/JointModels.ipynb
  docs/tutorials/ModelZoo.ipynb
  media/groupjointmodels.png
  tests/test_image.py
Labels: bug, enhancement, refactor, user experience

#70 updating joint modelling tutorial for new group model structure
  autoprof/fit/lm.py
  autoprof/models/core_model.py
  autoprof/models/group_model_object.py
  autoprof/models/model_object.py
  docs/tutorials/JointModels.ipynb
  tests/test_fit.py
  tests/test_image.py
  tests/test_image_list.py
Labels: user experience, unit test

#60 Added Type hints.
  .gitignore
  autoprof/fit/base.py
  autoprof/fit/hmc.py
  autoprof/fit/lm.py
  autoprof/image/__init__.py
  autoprof/image/model_image.py
  autoprof/image/target_image.py
Labels: documentation

#72 added doc string to _model_methods_.py file.
  autoprof/models/_model_methods.py
  autoprof/plots/__init__.py
  autoprof/plots/image.py
  autoprof/plots/profile.py
  autoprof/utils/angle_operations.py
  autoprof/utils/conversions/coordinates.py
  autoprof/utils/conversions/dict_to_hdf5.py
  autoprof/utils/conversions/functions.py
  autoprof/utils/conversions/optimization.py
  autoprof/utils/conversions/units.py
  autoprof/utils/initialize/__init__.py
  autoprof/utils/initialize/center.py
  autoprof/utils/initialize/construct_psf.py
  autoprof/utils/initialize/initialize.py
  autoprof/utils/initialize/segmentation_map.py
  autoprof/utils/interpolate.py
  autoprof/utils/isophote/ellipse.py
  autoprof/utils/isophote/extract.py
  autoprof/utils/isophote/integrate.py
  autoprof/utils/operations.py
  autoprof/utils/optimization.py
  autoprof/utils/parametric_profiles.py
Labels: documentation

#77 Formatted all the files using black.
  autoprof/AP_config.py
  autoprof/__init__.py
  autoprof/__main__.py
  autoprof/fit/__init__.py
  autoprof/fit/gradient.py
  autoprof/fit/hmc.py
  autoprof/fit/iterative.py
  autoprof/fit/lm.py
  autoprof/fit/mhmcmc.py
  autoprof/image/__init__.py
  autoprof/image/jacobian_image.py
  autoprof/image/model_image.py
  autoprof/image/target_image.py
  autoprof/image/window_object.py
  autoprof/models/_shared_methods.py
  autoprof/models/core_model.py
  autoprof/models/edgeon_model.py
  autoprof/models/exponential_model.py
  autoprof/models/flatsky_model.py
  autoprof/models/foureirellipse_model.py
  autoprof/models/galaxy_model_object.py
  autoprof/models/gaussian_model.py
  autoprof/models/group_model_object.py
  autoprof/models/model_object.py
  autoprof/models/moffat_model.py
  autoprof/models/nonparametric_model.py
  autoprof/models/nuker_model.py
  autoprof/models/parameter_object.py
  autoprof/models/planesky_model.py
  autoprof/models/psf_model.py
  autoprof/models/ray_model.py
  autoprof/models/sersic_model.py
  autoprof/models/sky_model_object.py
  autoprof/models/star_model_object.py
  autoprof/models/superellipse_model.py
  autoprof/models/warp_model.py
  autoprof/models/wedge_model.py
  autoprof/parse_config/basic_config.py
  autoprof/parse_config/galfit_config.py
  autoprof/plots/__init__.py
  autoprof/plots/image.py
  autoprof/plots/profile.py
  autoprof/plots/shared_elements.py
  autoprof/plots/visuals.py
Labels: documentation

#74 Unit tests for conversions/units and dict_to_hdf5, added h5py to requirements
  autoprof/utils/angle_operations.py
  autoprof/utils/conversions/dict_to_hdf5.py
  requirements.txt
  setup.py
  tests/test_utils.py
Labels: unit test

#78 Updates to jacobian system, ability to specify individual fit parameters
  .gitignore
  autoprof/fit/base.py
  autoprof/fit/gradient.py
  autoprof/fit/hmc.py
  autoprof/fit/iterative.py
  autoprof/fit/lm.py
  autoprof/fit/mhmcmc.py
  autoprof/image/image_object.py
  autoprof/image/jacobian_image.py
  autoprof/image/target_image.py
  autoprof/image/window_object.py
  autoprof/models/_shared_methods.py
  autoprof/models/core_model.py
  autoprof/models/edgeon_model.py
  autoprof/models/exponential_model.py
  autoprof/models/flatsky_model.py
  autoprof/models/gaussian_model.py
  autoprof/models/group_model_object.py
  autoprof/models/model_object.py
  autoprof/models/parameter_object.py
  autoprof/models/planesky_model.py
  autoprof/models/psf_model.py
  autoprof/plots/image.py
  autoprof/plots/profile.py
  autoprof/utils/angle_operations.py
  autoprof/utils/conversions/functions.py
  autoprof/utils/conversions/optimization.py
  autoprof/utils/conversions/units.py
  autoprof/utils/initialize/__init__.py
  autoprof/utils/initialize/center.py
  autoprof/utils/initialize/construct_psf.py
  autoprof/utils/initialize/segmentation_map.py
  autoprof/utils/isophote/extract.py
  autoprof/utils/parametric_profiles.py
  docs/tutorials/GettingStarted.ipynb
  docs/tutorials/GroupModels.ipynb
  docs/tutorials/JointModels.ipynb
  requirements.txt
  setup.py
  tests/test_fit.py
  tests/test_image.py
  tests/test_image_list.py
  tests/test_model.py
  tests/test_parameter.py
  tests/test_utils.py
  tests/test_window.py
  tests/test_window_list.py
  tests/utils.py
Labels: enhancement
